/* Catalogue Decap CMS : HTML construit avec textContent pour éviter l'injection. */
(()=>{'use strict';
const $=id=>document.getElementById(id);
const node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e};
const url=slug=>'article.html?slug='+encodeURIComponent(slug);
const dateFR=iso=>{const d=new Date(iso+'T12:00:00');return Number.isNaN(d.getTime())?iso:new Intl.DateTimeFormat('fr-CA',{day:'numeric',month:'long',year:'numeric'}).format(d)};
function image(src,alt,cls){const i=node('img',cls);i.src=src;i.alt=alt;i.loading='lazy';return i}
function author(post){const side=node('aside','blog-post-author');if(post.author_image)side.append(image(post.author_image,post.author,'blog-author-avatar'));else side.append(node('div','blog-avatar-fallback',(post.author||'M').trim().charAt(0).toUpperCase()));side.append(node('span','blog-author-name','Par '+post.author));const t=node('time','blog-author-date',dateFR(post.date));t.dateTime=post.date;side.append(t);return side}
function recent(posts){const target=$('madic-recent');if(!target)return;target.replaceChildren();posts.slice(0,5).forEach(p=>{const item=node('div','blog-recent-post');const a=node('a');a.href=url(p.slug);a.append(image(p.image,p.title));const box=node('div');const t=node('time','',dateFR(p.date));t.dateTime=p.date;const h=node('h4');const link=node('a','',p.title);link.href=url(p.slug);h.append(link);box.append(t,h);item.append(a,box);target.append(item)})}
function archives(posts){const target=$('madic-archives');if(!target)return;target.replaceChildren();const counts=new Map();posts.forEach(p=>{const key=p.date.slice(0,7);counts.set(key,(counts.get(key)||0)+1)});for(const [key,count] of counts){const li=node('li');const a=node('a','',new Intl.DateTimeFormat('fr-CA',{month:'long',year:'numeric'}).format(new Date(key+'-15T12:00:00')));a.href='blogue.html?archive='+encodeURIComponent(key);li.append(a,node('span','',`(${count})`));target.append(li)}}
function list(posts){const target=$('madic-articles');if(!target)return;target.replaceChildren();const archive=new URLSearchParams(location.search).get('archive');const shown=archive?posts.filter(p=>p.date.startsWith(archive)):posts;if(!shown.length){target.append(node('p','','Aucun article dans cette période.'));return}shown.forEach(p=>{const art=node('article','blog-post');art.id='article-'+p.slug;art.append(author(p));const content=node('div','blog-post-content');const imgLink=node('a','blog-post-image');imgLink.href=url(p.slug);imgLink.append(image(p.image,p.title));content.append(imgLink,node('div','blog-post-category',p.category));const h=node('h2');const a=node('a','',p.title);a.href=url(p.slug);h.append(a);content.append(h,node('p','blog-post-excerpt',p.summary));const foot=node('div','blog-post-footer');const read=node('a','blog-readmore','Lire la suite →');read.href=url(p.slug);foot.append(read);content.append(foot);art.append(content);target.append(art)})}
function single(posts){const target=$('madic-articles');if(!target)return;target.replaceChildren();const slug=new URLSearchParams(location.search).get('slug');const p=posts.find(item=>item.slug===slug);if(!p){target.append(node('p','','Article introuvable.'));return}document.title=p.title+' | MADIC';const art=node('article','blog-post');art.append(author(p));const content=node('div','blog-post-content');const cover=node('div','blog-post-image');cover.append(image(p.image,p.title));content.append(cover,node('div','blog-post-category',p.category),node('h2','',p.title));const body=node('div','blog-single-body');if(typeof marked!=='undefined'&&typeof DOMPurify!=='undefined'){body.innerHTML=DOMPurify.sanitize(marked.parse(p.body||''))}else{(p.body||'').split(/\n\s*\n/).forEach(t=>body.append(node('p','',t)))}content.append(body);const back=node('a','blog-readmore','← Retour au blogue');back.href='blogue.html';content.append(back);art.append(content);target.append(art)}
fetch('data/articles.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Catalogue indisponible');return r.json()}).then(posts=>{if(!Array.isArray(posts))throw Error('Catalogue invalide');recent(posts);archives(posts);if(document.body.dataset.blogPage==='article')single(posts);else list(posts)}).catch(()=>{const t=$('madic-articles');if(t)t.replaceChildren(node('p','','Impossible de charger les articles. Vérifiez data/articles.json et lancez un serveur web.'))});
})();
